# Generated by Django 4.2.2 on 2023-06-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emial", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=254)),
                ("token", models.CharField(max_length=100)),
            ],
        ),
    ]
