# Generated by Django 4.2.2 on 2023-06-30 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuarios",
            old_name="emial",
            new_name="email",
        ),
    ]
