# Generated by Django 4.2.2 on 2023-06-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aplicacion1", "0002_rename_entregadp_pedidos_entregado_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Articulos",
        ),
        migrations.DeleteModel(
            name="Pedidos",
        ),
        migrations.RenameField(
            model_name="clientes",
            old_name="telefono",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="clientes",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="clientes",
            name="email",
        ),
        migrations.RemoveField(
            model_name="clientes",
            name="nombre",
        ),
        migrations.AddField(
            model_name="clientes",
            name="category",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientes",
            name="name",
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
